export const LLM_MODEL = "llama3-70b-8192";
export const LLM_TEMPERATURE = 1;

export const discussions = [
  {
    id: 1,
    title: "Backpack Data Explained - How To Find Signal",
    author: "Chris Deotte",
    category: "Backpack Prediction Challenge",
    lastComment: { by: "Akai Red", time: "8h ago" },
    comments: 16,
    votes: 35,
  },
  {
    id: 2,
    title: "Starter Notebook - RAPIDS v25.02 - [LB 38.847]",
    author: "Chris Deotte",
    category: "Backpack Prediction Challenge",
    lastComment: { by: "Иван Третьяков", time: "10m ago" },
    comments: 25,
    votes: 40,
  },
  {
    id: 3,
    title: "Vote for the best meme",
    author: "Alexandre Le Mercier",
    category: "LLMs - You Can't Please Them All",
    lastComment: { by: "Gerwyn", time: "7h ago" },
    comments: 15,
    votes: 7,
  },
  {
    id: 4,
    title: "Understanding Quantum Mechanics",
    author: "Dr. Jane Smith",
    category: "Physics",
    lastComment: { by: "John Doe", time: "1d ago" },
    comments: 10,
    votes: 50,
  },
  {
    id: 5,
    title: "The Basics of Calculus",
    author: "Prof. Alan Turing",
    category: "Mathematics",
    lastComment: { by: "Alice", time: "2h ago" },
    comments: 20,
    votes: 45,
  },
  {
    id: 6,
    title: "How to Write a Research Paper",
    author: "Dr. Emily Davis",
    category: "Education",
    lastComment: { by: "Bob", time: "3d ago" },
    comments: 8,
    votes: 30,
  },
  {
    id: 7,
    title: "Introduction to Machine Learning",
    author: "Prof. Andrew Ng",
    category: "Computer Science",
    lastComment: { by: "Charlie", time: "5h ago" },
    comments: 18,
    votes: 60,
  },
  {
    id: 8,
    title: "The History of Ancient Civilizations",
    author: "Dr. Sarah Johnson",
    category: "History",
    lastComment: { by: "David", time: "1w ago" },
    comments: 12,
    votes: 25,
  },
  {
    id: 9,
    title: "Exploring the Solar System",
    author: "Dr. Neil Armstrong",
    category: "Astronomy",
    lastComment: { by: "Eve", time: "6h ago" },
    comments: 22,
    votes: 55,
  },
  {
    id: 10,
    title: "The Fundamentals of Organic Chemistry",
    author: "Prof. Marie Curie",
    category: "Chemistry",
    lastComment: { by: "Frank", time: "2d ago" },
    comments: 14,
    votes: 40,
  },
  {
    id: 11,
    title: "Understanding Artificial Intelligence",
    author: "Dr. Alan Turing",
    category: "Computer Science",
    lastComment: { by: "Grace", time: "4h ago" },
    comments: 30,
    votes: 70,
  },
  {
    id: 12,
    title: "The Basics of Genetics",
    author: "Dr. Gregor Mendel",
    category: "Biology",
    lastComment: { by: "Hank", time: "3d ago" },
    comments: 16,
    votes: 35,
  },
  {
    id: 13,
    title: "Learning Python Programming",
    author: "Prof. Guido van Rossum",
    category: "Computer Science",
    lastComment: { by: "Ivy", time: "1h ago" },
    comments: 25,
    votes: 65,
  },
  {
    id: 14,
    title: "The Theory of Relativity",
    author: "Dr. Albert Einstein",
    category: "Physics",
    lastComment: { by: "Jack", time: "2d ago" },
    comments: 20,
    votes: 50,
  },
  {
    id: 15,
    title: "Introduction to Data Science",
    author: "Prof. DJ Patil",
    category: "Data Science",
    lastComment: { by: "Karen", time: "5h ago" },
    comments: 18,
    votes: 55,
  },
  {
    id: 16,
    title: "The Basics of Microeconomics",
    author: "Dr. Adam Smith",
    category: "Economics",
    lastComment: { by: "Leo", time: "1w ago" },
    comments: 10,
    votes: 30,
  },
  {
    id: 17,
    title: "Understanding Human Anatomy",
    author: "Dr. Henry Gray",
    category: "Biology",
    lastComment: { by: "Mia", time: "3d ago" },
    comments: 12,
    votes: 40,
  },
  {
    id: 18,
    title: "The Basics of Electrical Engineering",
    author: "Prof. Nikola Tesla",
    category: "Engineering",
    lastComment: { by: "Nina", time: "6h ago" },
    comments: 22,
    votes: 50,
  },
  {
    id: 19,
    title: "Introduction to Philosophy",
    author: "Dr. Socrates",
    category: "Philosophy",
    lastComment: { by: "Oscar", time: "2d ago" },
    comments: 14,
    votes: 35,
  },
  {
    id: 20,
    title: "The Fundamentals of Statistics",
    author: "Prof. Ronald Fisher",
    category: "Mathematics",
    lastComment: { by: "Paul", time: "4h ago" },
    comments: 20,
    votes: 45,
  },
];
